Repository MihaMoor/Library, pull requests merged in 2024-05, with the labels that each got.

#16 fix: исправлена генерация дизайнера при создании файла локлизации для проектов API
  src/Book/Book.API/Book.API.csproj
  src/Book/Book.API/Resources/Localizations/Localization.Designer.cs
  src/Magazine/Magazine.API/Magazine.API.csproj
  src/Magazine/Magazine.API/Resources/Localizations/Localization.Designer.cs
  src/User/User.API/Resources/Localizations/Localization.Designer.cs
  src/User/User.API/User.API.csproj
Labels: bug

#15 update: обновлены доменные модели микросервиса Magazine
  src/Magazine/Magazine.API/Program.cs
  src/Magazine/Magazine.Domain/AggregatesModel/Magazine/Magazine.cs
  src/Magazine/Magazine.Domain/AggregatesModel/PublishingHouse/PublishingHouse.cs
  src/Magazine/Magazine.Domain/Class1.cs
  src/Magazine/Magazine.Domain/Magazine.Domain.csproj
Labels: enhancement, question

#17 feature: созданы тесты, обновлена логика сравнения
  .nuke/parameters.json
  Library.sln
  build.cmd
  build.ps1
  build.sh
  src/Book/Book.Domain/AggregatesModel/AuthorAggregate/Author.cs
  src/Book/Book.Domain/AggregatesModel/BookAggregate/Book.cs
  src/Book/Book.Domain/AggregatesModel/PublishingHouseAggregate/PublishingHouse.cs
  src/Book/Book.UnitTests/Book.UnitTests.csproj
  src/Book/Book.UnitTests/DomainModels/AuthorTest.cs
  src/Book/Book.UnitTests/DomainModels/PublishingHouseTest.cs
Labels: enhancement

#14 feature: настроен CQRS для Book
  README.md
  docker-compose.yml
  src/Book/Book.API/Application/Queries/Book/BookQueries.cs
  src/Book/Book.API/Application/Queries/Book/IBookQueries.cs
  src/Book/Book.API/Application/Queries/QueryService.cs
  src/Book/Book.API/Application/ViewModels/BookViewModel.cs
  src/Book/Book.API/Book.API.csproj
  src/Book/Book.API/Book.API.http
  src/Book/Book.API/Controllers/BookControllers.cs
  src/Book/Book.API/Extensions/BookExtensions.cs
  src/Book/Book.API/Program.cs
  src/Book/Book.API/Resources/Localizations/Localization.Designer.cs
  src/Book/Book.API/WeatherForecast.cs
  src/Book/Book.API/appsettings.json
  src/Book/Book.Domain/Interfaces/IQueries.cs
  src/Book/Book.Infrastructure/Book.Infrastructure.csproj
  src/Book/Book.Infrastructure/BookContext.cs
  src/Book/Book.Infrastructure/Class1.cs
  src/Magazine/Magazine.API/Resources/Localizations/Localization.Designer.cs
  src/User/User.API/Resources/Localizations/Localization.Designer.cs
Labels: enhancement
